apiVersion: v1
kind: Service
metadata:
  name: carapps
  labels:
    app: carapp
spec:
  selector:
    app: carapp
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31200
  type: LoadBalancer
